#!/bin/sh

trap 'rm -f test.tmp' EXIT

retval=$("$@" -o test.tmp 2>&1)

echo "$retval" >&2

if [ $? -ne 0 ]; then
	exit 1
elif echo "$retval" | grep 'SKIPTEST'; then
	exit 77
elif echo "$retval" | grep -q 'warning'; then
	exit 1
else
	exit 0
fi
